config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'urls#index'
  resources :urls
  get '/urls/:id/short' => 'urls#short'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
	before_create :shorten #before i save go do shorten 
	validates :long_url, presence: { message: "is required! " }, format: { :with => URI::regexp(%w(http https)) }
    validates :long_url, uniqueness: true


	after_validation :smart_add_url_protocol

	def shorten
      self.short_url = [*('a'..'z'),*('0'..'9')].shuffle[0,7].join
	end

	protected

	def smart_add_url_protocol
 	  unless self.long_url[/\Ahttp:\/\//] || self.long_url[/\Ahttps:\/\//]
   	    self.long_url = "http://#{self.long_url}"
 	  end
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
    @urls = Url.all
    @url = Url.new
  end

  def show
    @url = Url.find(params[:id])
  end

  # def new
  #   @url = Url.new
  # end
  
  def create
    @url = Url.new(url_params)
    @url.shorten
    if @url.save
      redirect_to @url  
    else
      render 'new'
    end   
  end

  def destroy
  	@url = Url.find(params[:id])
    @url.destroy
    redirect_to urls_path
  end

  def short
    url = Url.find(params[:id])
    redirect_to url.long_url    
  end 

  private 

  def url_params
    params.require(:url).permit(:long_url)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bitsy | URL Fun-Sized</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/_form.html.erb
<%= form_for @url do |f| %>
  <p>
    <%= f.text_field :long_url, placeholder: "Paste a link to shorten it"%>
  </p>

  <p>
    <%= f.submit "SHORTEN" %>
  </p>
    <% end %>

app/views/urls/index.html.erb
<h1>Bitsy | URL Fun-Sized</h1>

<%= render 'form' %>

<table>
<tr>
<th>Your URL</th>
<th>Bitsy URL</th>
</tr>

<%  @urls.each do |url| %>
    <tr>
    <td> <a href = <%= url.long_url %> ><%= url.long_url %></a></td>
    <td> <%= link_to url.short_url, controller: :urls, action: :short, id: url %></a> </td>
    <td> <%= link_to 'Show', url_path(url) %> </td>
    <td><%= link_to 'Delete', url_path(url), method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>   
<% end %>
</table>

app/views/urls/new.html.erb
<h3>This is urls/new</h3>
<%= render 'form' %>
<%= link_to 'Back', urls_path %>

app/views/urls/show.html.erb
 <h3>This is urls/show</h3>
    <p><%= @url.long_url %></p>
    <p><%= @url.short_url %></p>
    
    <%= link_to 'Back', urls_path %>